### ISSUE TITLE
Static DynamicCommand: how to understand what command overload the player has chosen?

### ISSUE THREAD

**Issue by S3v3Nice** [LiteLDev/LiteLoader.NET#11]
Suppose there are two command overloads. Both of them have an enum as the first parameter (both enums are different). How can we figure out which overload (enum) the player has chosen, and which case to handle in Execute()? 

I thought it would be possible to make the type nullable for the enum variable. Then if the variable is null, it means the variable has not been set, hence the player has chosen a different overload. But then an exception is thrown:
```
ERROR [LiteLoader] Uncaught C++ Exception Detected!
ERROR [LiteLoader] Error: Code [2] Enum Nullable`1not found in command and BDS
ERROR [LiteLoader] In Function (DynamicCommand::_setup - templatecmd)
ERROR [LiteLoader] In Plugin <TemplatePlugin>
ERROR [LiteLoader] Uncaught C++ Exception Detected!
ERROR [LiteLoader] Error: Code [2] Command "templatecmd" setup failed
ERROR [LiteLoader] In Function (DynamicCommand::_setup - templatecmd)
ERROR [LiteLoader] In Plugin <TemplatePlugin>
```

**Comment by Pd233** [comment]
This feature is under designing, We will try to solve it.
![IMG_1439(20220628-153437)](https://user-images.githubusercontent.com/69450129/176161828-ad410e31-3f38-48fb-b6f2-9acdeb799ddc.JPG)

**Comment by Pd233** [comment]
Now you can use KeyValuePair<bool,ParameterType> as a Parameter to determine if this parameter has been set.
