### ISSUE TITLE
将插件分离至独立加载上下文

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader.NET#13]
有关文档：https://docs.microsoft.com/zh-cn/dotnet/standard/assembly/unloadability

**Comment by Yushu2606** [comment]
还需要接入LL的相关命令

**Comment by Pd233** [comment]
现阶段Hook好像不能卸载。。。直接卸载插件的话估计会炸

**Comment by Pd233** [comment]
啥时候能卸载hook了就可以做了（

**Comment by Yushu2606** [comment]
LiteLDev/LiteLoaderBDS #790

**Comment by Yushu2606** [comment]
可以先整热加载qwq

**Comment by Yushu2606** [comment]
加/卸载可能需要等待https://github.com/LiteLDev/LiteLoaderBDS/issues/1047 完成
