### ISSUE TITLE
修复SDK推送

### ISSUE THREAD

**Issue by Pd233** [LiteLDev/LiteLoader.NET#17]
话说这个Action能不能修一修（
Actions里全是红叉叉
草

**Comment by StarsDream00** [comment]
来个会的git的人看看到底为什么推不上去呜呜

**Comment by Pd233** [comment]
![AF6848CC0D364BA497EFF029B92B7313](https://user-images.githubusercontent.com/69450129/178789702-900c3a52-372f-42dd-a2c0-a7f609769ad3.png)

**Comment by StarsDream00** [comment]
应该需要在ll组织下创建仓库才行吧

**Comment by Yushu2606** [comment]
草它自己关了（

**Comment by StarsDream00** [comment]
暂时搁置
