### ISSUE TITLE
无法加载LiteLoader.NET

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader.NET#59]
### 操作系统

Windows

### LiteLoader版本

2.12.3

### LiteLoader.NET版本

2.12.1-pre.1

### BDS版本

1.19.73

### 发生了什么？

04.04 21:21:01 [服务器] ERROR [LiteLoader Plugin <LiteLoader.NET> throws an exception in onPostInit!
04.04 21:21:01 [服务器] ERROR [LiteLoader Fail to init plugin <LiteLoader.NET>!

### 复现此问题的步骤

在Rhymc.com装载LiteLoader.net并加载插件的时候遇到这个问题，插件也没法加载

### 有关的日志/输出

```raw
04.04 21:21:01 [服务器] ERROR [LiteLoader Plugin <LiteLoader.NET> throws an exception in onPostInit!
04.04 21:21:01 [服务器] ERROR [LiteLoader Fail to init plugin <LiteLoader.NET>!
```

**Comment by Yushu2606** [comment]
一眼没装.NET运行时

**Comment by ghost** [comment]
面板服怎么装

**Comment by Yushu2606** [comment]
安装LLNETPreloader，然后下载[这个](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-7.0.4-windows-x64-binaries)解压放`plugins/lib/managed/dotnet`里

**Comment by ghost** [comment]
还是没法加载

**Comment by Yushu2606** [comment]
@reskevin 重新看下我回复

**Comment by reskevin** [comment]
还是运行不了

**Comment by ghost** [comment]
04.04 22:10:50 [服务器] ERROR [PreLoader Can't load plugins/LLNETPreLoader.dll !
04.04 22:10:50 [服务器] ERROR [PreLoader Error code: 126 !
04.04 22:10:50 [服务器] ERROR [PreLoader 找不到模块。
没用

**Comment by LazuliKao** [comment]
核对一下以下步骤

- ### 放置`.NET 7.0`运行时二进制文件
地址：https://dotnet.microsoft.com/zh-cn/download/dotnet/7.0
- - 找到`.NET 运行时 7.0.x`，你会看到如下内容
    >#### 下载 .NET 7.0 Runtime (v7.0.x) 版
    ><table>
    ><tr><th>平台</th><th>安装程序</th><th>二进制文件</th></tr>
    ><tr><td>Linux</td><td>包管理器说明</td><td>Arm32 | Arm32 Alpine | Arm64 | Arm64 Alpine | x64 | x64 Alpine</td></tr>
    ><tr><td>macOS</td><td>Arm64 | x64</td><td>Arm64 | x64</td></tr>
    ><tr><td>Windows</td><td>Arm64 | x64 | x86 | winget 指令</td><td>Arm64 | <a href="https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-7.0.2-windows-x64-binaries">x64</a> | x86</td></tr>
    ><tr><td>全部</td><td>dotnet-install scripts</td><td></td></tr>
    ></table>
  - 不论是基于Wine还是Windows的面板，你需要的都是`Windows`行`二进制文件`列的`x64`文件
  - 下载到的是个zip文件
  - 到BDS安装目录的`plugins\lib`文件夹下，创建一个叫`managed`的文件夹，进去再创建一个叫`dotnet`文件夹，将zip所有文件解压到此文件夹，也就是说`plugins\lib\managed\dotnet`文件夹下应该有`dotnet.exe`和`shared`文件夹
- ### 放置nethost.dll
    - [地址](https://github.com/LiteLDev-NET/Loader/blob/main/lib/nethost.dll)
    - [地址(直接下载)](https://raw.githubusercontent.com/LiteLDev-NET/Loader/main/lib/nethost.dll)
- ### 放置Ijwhost.dll
    - `Ijwhost.dll`放到BDS安装目录的`plugins\lib`文件夹下
    - (下载地址： LLNET的压缩包内lib文件夹下自带了，放上去就行了)
- ### 运行

**Comment by Yushu2606** [comment]
@reskevin 缺了nethost

**Comment by ghost** [comment]
nethost放哪？

**Comment by Yushu2606** [comment]
`plugins\lib`

**Comment by ghost** [comment]
[LLNETPreLoader Cannot fine global .NET runtime, try using the local runtime.

**Comment by reskevin** [comment]
![image](https://user-images.githubusercontent.com/95084801/229822488-1fb22e68-4a8c-4ba9-a025-b229a65c2e7c.png)

**Comment by ghost** [comment]
在这一行就卡住了

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/95084801/229823657-38a57ed4-aa98-4da1-864f-46346ef2cb24.png)

**Comment by StarsDream00** [comment]
@reskevin Pd

**Comment by Pd233** [comment]
有可能是wine版本过低？

**Comment by ghost** [comment]
这个我不知道啊，用的是Rhymc的面板服

**Comment by Yushu2606** [comment]
建议联系旋律云更新wine

**Comment by ghost** [comment]
怎么联系呢？

**Comment by Yushu2606** [comment]
> 怎么联系呢？

找客服

**Comment by ghost** [comment]
客服说Wine已经是最新版本了

**Comment by Pd233** [comment]
> 客服说Wine已经是最新版本了

[LLNETPreLoader.zip](https://github.com/LiteLDev/LiteLoader.NET/files/11156944/LLNETPreLoader.zip)
试试这个重新编译的PreLoader？

**Comment by Yushu2606** [comment]
还有问题可以跟评
