### ISSUE TITLE
System.InvalidCastException: 'LLNET.Event.__EventListener<Event::PlayerJoinEvent>' to 'EventListener'

### ISSUE THREAD

**Issue by S3v3Nice** [LiteLDev/LiteLoader.NET#9]
### Operating System
Windows 10

### LiteLoader version
v2.3.1-pre-2

### BDS version
Version 1.19.2.02(ProtocolVersion 527)

### What happened?
The error occurs when starting a server with the plugin enabled, which subscribes to any events (in my case, PlayerJoinEvent).
```
ERROR [LiteLoader.NET] Uncaught System.InvalidCastException Detected!
ERROR [LiteLoader.NET] System.InvalidCastException: Unable to cast object of type 'LLNET.Event.__EventListener<Event::PlayerJoinEvent>' to type 'EventListener'.
   at LLNET.Event.PlayerJoinEvent.Subscribe(EventHandler callback)
   at TemplatePlugin.TemplatePlugin.OnInitialize()
   at LoadByCustomEntry(Logger* logger, Assembly Asm)
```

### Steps to reproduce
1. Create a plugin that subscribes to any event (e.g. PlayerJoinEvent)
2. Put the plugin in the plugins folder and run the server. An exception will be thrown while loading your plugin.

**Comment by Pd233** [comment]
The problem has been fixed, please update the latest release.
